#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

$app = new Application();

$env = new Dotenv();
$env->load(__DIR__ . '/.env');

$parameters = [
    'user' => $_ENV['DB_USER'],
    'password' => $_ENV['DB_PASSWORD'],
    'host' => $_ENV['DB_HOST'],
    'name' => $_ENV['DB_NAME'],
    'port' => $_ENV['DB_PORT'],
];

$app->add(new TableListCommand($parameters));
$app->add(new TableAllCommand($parameters));

$app->run();
