#!/usr/bin/env php
<?php

use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Application;

// include the autoloader
require __DIR__.'/vendor/autoload.php';

// load the configuration
$env = new Dotenv();
$env->load(__DIR__ . '/.env');

$app = new Application();

$app->add(new TableDropCommand());
$app->add(new TableListCommand());
// $app->add(new TableAllCommand($parameters));

$app->run();
